version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          ELASTIC_HOST: "http://127.0.0.1:9200"
          IOC_ELASTIC_HOST: "127.0.0.1:9500" # this must point to transport tcp port (NOT rest port)
          IOC_ELASTIC_HOST_REST: "http://127.0.0.1:9400" # for tests only
          ELASTIC_QUERY_MAX_SIZE: 10000

      # Elastic for logs and dns
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        environment:
          XPACK_MONITORING_ENABLED: 'false'
          discovery.type: single-node
          cluster.name: archive
          bootstrap.memory_lock: 'true'
          ES_JAVA_OPTS: -Xms256m -Xmx256m

      # Elastic for iocs
      - image: harbor.whalebone.io/whalebone/ioc-archive-testing-elastic:1.7.1
        auth:
          username: $HARBOR_USER      #harbor credentials must be set in context in CI admin UI manually
          password: $HARBOR_PASSWORD
        environment:
          ES_CLUSTER: "archive"
          ES_HEAP_SIZE: "256m"
          ES_INT: "lo"
          ES_SERVICE_NAME: "archive"
          ES_NODE_MASTER: "true"
          ES_NODE_DATA: "true"
          ES_GROOVY_ENABLED: "true"
          ES_SCRIPT_DISABLE: "false"
          ES_MINIMUM_MASTER_NODES: "1"
          ES_HTTP_PORT: 9400
          ES_TRANSPORT_TCP_PORT: 9500

    working_directory: ~/public-api

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mkdir -p integration-tests/target/surefire-reports # create the test results directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          keys:
          - public-api-{{ checksum "pom.xml" }}
          - public-api-
      
      - run:
          name: build shaded elasticsearch library for ioc archive
          command: cd elasticsearch-for-archive && mvn clean install -DskipTests

      - run:
          name: build public api
          command: mvn clean install -DskipTests
      
      - save_cache: # saves the project dependencies
          key: public-api
          paths:
            - ~/.m2

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: wait for logs elastic
          command: dockerize -wait http://localhost:9200 -timeout 1m
      - run:
          name: wait for ioc archive
          command: dockerize -wait http://localhost:9400 -timeout 1m

      - run:
          name: set doc mappings
          command: |
            curl -XPUT -H 'Content-Type: application/json' localhost:9200/_template/logs -d @integration-tests/src/test/resources/logs-template.json
            curl -XPUT -H 'Content-Type: application/json' localhost:9200/_template/passivedns -d @integration-tests/src/test/resources/passivedns-template.json
            curl -XPUT -H 'Content-Type: application/json' localhost:9200/_template/dnssec -d @integration-tests/src/test/resources/dnssec-template.json
            curl -XPUT -H 'Content-Type: application/json' localhost:9200/_template/resolver -d @integration-tests/src/test/resources/resolver-template.json
            curl -XPUT -H 'Content-Type: application/json' localhost:9400/_template/iocs -d @integration-tests/src/test/resources/iocs-template.json

      - run:
          name: run tests
          command: mvn integration-test -Parq-wildfly-managed

      - store_test_results:
          path: integration-tests/target/surefire-reports
