version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          ELASTIC_HOST: "http://127.0.0.1:9200"
          JWT_SECRET: "test"
          AES_KEY: "testtesttesttest"
          AES_IV: "1234567890123456"

      # ELASTIC
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        environment:
          XPACK_MONITORING_ENABLED: 'false'
          discovery.type: single-node
          cluster.name: archive
          bootstrap.memory_lock: 'true'
          ES_JAVA_OPTS: -Xms256m -Xmx256m

    working_directory: ~/public-api

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          keys:
          - public-api-{{ checksum "pom.xml" }}
          - public-api-
      
      - run: mvn clean install -DskipTests
      
      - save_cache: # saves the project dependencies
          key: public-api
          paths:
            - ~/.m2

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: wait for archive
          command: dockerize -wait http://localhost:9200 -timeout 1m

      # setup the elastic mappings
      - run: curl -XPUT -H "Content-Type: application/json" localhost:9200/_template/logs -d @integration-tests/src/test/resources/logs-template.json
      - run: curl -XPUT -H "Content-Type: application/json" localhost:9200/_template/passivedns -d @integration-tests/src/test/resources/passivedns-template.json
      - run: curl -XPUT -H "Content-Type: application/json" localhost:9200/_template/dnssec -d @integration-tests/src/test/resources/dnssec-template.json

      # run tests!
      - run: mvn integration-test -Parq-wildfly-managed

      - store_test_results:
          path: integration-tests/target/surefire-reports
