version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          ELASTIC_CLUSTER: "archive"
          ELASTIC_HOST: "127.0.0.1"
          ELASTIC_PORT: "9300"
          ELASTIC_REST_PORT: "9200"
          JWT_SECRET: "test"
          AES_KEY: "testtesttesttest"
          AES_IV: "1234567890123456"

      # ELASTIC
      # Image repo: https://github.com/hugeox/elastic-docker
      - image: hugeox/sinkit-elastic:1.0
        environment:
          ES_CLUSTER: "archive"
          ES_HEAP_SIZE: "256m"
          ES_INT: "lo"
          ES_SERVICE_NAME: "archive"
          ES_NODE_MASTER: "true"
          ES_NODE_DATA: "true"
          ES_GROOVY_ENABLED: "true"
          ES_SCRIPT_DISABLE: "false"
          ES_MINIMUM_MASTER_NODES: "1"

    working_directory: ~/public-api

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          keys:
          - public-api-{{ checksum "pom.xml" }}
          - public-api-
      
      - run: mvn clean install -DskipTests
      
      - save_cache: # saves the project dependencies
          key: public-api
          paths:
            - ~/.m2

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: wait for archive
          command: dockerize -wait http://localhost:9200 -timeout 1m

      # setup the elastic mappings
      - run: curl -XPUT localhost:9200/_template/logs -d @integration-tests/src/test/resources/logs-template.json
      - run: curl -XPUT localhost:9200/_template/passivedns -d @integration-tests/src/test/resources/passivedns-template.json

      # run tests!
      - run: mvn integration-test -Parq-wildfly-managed

      - store_test_results:
          path: integration-tests/target/surefire-reports
